# Generated by Django 5.2.5 on 2026-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12557_add_language_datatype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardxnodexwidget",
            name="sortorder",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddConstraint(
            model_name="cardxnodexwidget",
            constraint=models.UniqueConstraint(
                fields=("node", "widget"), name="unique_node_widget"
            ),
        ),
    ]
